//! Differential gate: the Rust enumerator must reproduce, bit-for-bit, every row
//! of the candidate caches generated by the trusted Python (numpy/numba) pipeline.
//! This is the equivalence proof that licenses deleting the Python enumerator.

use std::path::PathBuf;

use pokemon_rng::cache;
use pokemon_rng::enumerate::{enum_candidate, Filter};

const TID: u16 = 51376;
const SID: u16 = 36462;

fn repo_root() -> PathBuf {
    // crates/pokemon-rng -> repo root
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn check_cache(name: &str) {
    let path = repo_root().join(name);
    if !path.exists() {
        eprintln!("skip {name}: not present");
        return;
    }
    let set = cache::load(&path).unwrap_or_else(|e| panic!("load {name}: {e}"));
    assert!(!set.is_empty(), "{name} empty");
    // All slots/natures allowed: enum_candidate must still reproduce each row's
    // pid/nature/iters/o1..o4 exactly from G alone.
    let f = Filter::new(
        TID,
        SID,
        &(0..12).collect::<Vec<_>>(),
        &(0..25).collect::<Vec<_>>(),
    );
    for i in 0..set.len() {
        let want = set.candidate(i);
        let got = enum_candidate(want.g, &f)
            .unwrap_or_else(|| panic!("{name} row {i}: G=0x{:08X} produced no candidate", want.g));
        assert_eq!(got, want, "{name} row {i}: G=0x{:08X} mismatch", want.g);
    }
    eprintln!("{name}: {} rows reproduced bit-identically", set.len());
}

/// Full 2^32 scan must find EXACTLY the cached candidate set (no misses/extras).
/// Run explicitly: `cargo test --release --test differential -- --ignored --nocapture`.
#[test]
#[ignore]
fn full_scan_matches_clefairy_cache() {
    use std::time::Instant;
    let path = repo_root().join("cache_clefairy.npz");
    if !path.exists() {
        eprintln!("skip: cache_clefairy.npz not present");
        return;
    }
    let set = cache::load(&path).unwrap();
    let f = Filter::new(TID, SID, &[7], &(0..25).collect::<Vec<_>>());
    let t0 = Instant::now();
    let mut found = pokemon_rng::enumerate(&f);
    let secs = t0.elapsed().as_secs_f64();
    found.sort_by_key(|c| c.g);
    let mut want_g = set.g.clone();
    want_g.sort_unstable();
    let got_g: Vec<u64> = found.iter().map(|c| c.g as u64).collect();
    eprintln!(
        "full 2^32 clefairy scan: {} candidates in {:.1}s",
        found.len(),
        secs
    );
    assert_eq!(got_g, want_g, "full-scan G set differs from cache");
}

#[test]
fn enumerator_matches_python_caches() {
    let mut any = false;
    for name in [
        "cache_clefairy.npz",
        "cache_nidoranm.npz",
        "cache_spearow.npz",
    ] {
        if repo_root().join(name).exists() {
            any = true;
        }
        check_cache(name);
    }
    assert!(any, "no caches found to differential-test against");
}
